import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword01widget/generated/GeneratedDeviceFrameComponentsWidget9.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword01widget/generated/GeneratedOneTimePasswordWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword01widget/generated/GeneratedDidntreceiveOTPClickheretoresendWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword01widget/generated/GeneratedButton_reset_pwdWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword01widget/generated/GeneratedUndraw_forgot_password_re_hxwm1Widget2.dart';

/* Frame Forgot Password 01
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPassword01Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 26.0,
                child: GeneratedDidntreceiveOTPClickheretoresendWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 40.0,
                child: GeneratedButton_reset_pwdWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 396.61572265625,
                right: null,
                bottom: null,
                width: 356.0,
                height: 154.0,
                child: GeneratedOneTimePasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 239.2450714111328,
                child: GeneratedUndraw_forgot_password_re_hxwm1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget9(),
              )
            ]),
      ),
    ));
  }
}
