import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedBroadcast_on_homeWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedSensor_doorWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedVertical_shades_closedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedGas_meterWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedBlindsWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedRoller_shadesWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedSensor_windowWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedEnergy_savings_leafWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedMode_fan_offWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedBlinds_closedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedElectric_meterWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedHomeWidget28.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedVertical_shadesWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedNest_cam_wired_standWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedHeat_pumpWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedAuto_modeWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedRoller_shades_closedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedBroadcast_on_personalWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedPropaneWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedPropane_tankWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedElectric_boltWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedSensor_occupiedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedCurtains_closedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedWind_powerWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedShield_moonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedCurtainsWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedSolar_powerWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedhomewidget27/generated/GeneratedOil_barrelWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget27 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 504.0,
        height: 240.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 19.0,
                child: GeneratedHomeWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAuto_modeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBlindsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBlinds_closedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBroadcast_on_homeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBroadcast_on_personalWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCurtainsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCurtains_closedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedElectric_boltWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedElectric_meterWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEnergy_savings_leafWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGas_meterWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHeat_pumpWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMode_fan_offWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNest_cam_wired_standWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedOil_barrelWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPropaneWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPropane_tankWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRoller_shadesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRoller_shades_closedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSensor_doorWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSensor_occupiedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSensor_windowWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedShield_moonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSolar_powerWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedVertical_shadesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedVertical_shades_closedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWind_powerWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
