import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget3.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget6.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget7.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget9.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget8.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget5.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget4.dart';
import 'package:flutterapp/gradtrackapp/generatedlabelswidget/generated/GeneratedLabelsWidget2.dart';

/* Group Labels
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLabelsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1984.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 8435.0,
                    height: 1984.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 113.0,
                            height: 708.0,
                            child: GeneratedLabelsWidget1(),
                          ),
                          Positioned(
                            left: 790.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 113.0,
                            height: 708.0,
                            child: GeneratedLabelsWidget2(),
                          ),
                          Positioned(
                            left: 7502.0,
                            top: 12.0,
                            right: null,
                            bottom: null,
                            width: 60.0,
                            height: 464.0,
                            child: GeneratedLabelsWidget3(),
                          ),
                          Positioned(
                            left: 8320.0,
                            top: 12.0,
                            right: null,
                            bottom: null,
                            width: 60.0,
                            height: 464.0,
                            child: GeneratedLabelsWidget4(),
                          ),
                          Positioned(
                            left: 7510.0,
                            top: 635.0,
                            right: null,
                            bottom: null,
                            width: 82.0,
                            height: 584.0,
                            child: GeneratedLabelsWidget5(),
                          ),
                          Positioned(
                            left: 8322.0,
                            top: 635.0,
                            right: null,
                            bottom: null,
                            width: 82.0,
                            height: 584.0,
                            child: GeneratedLabelsWidget6(),
                          ),
                          Positioned(
                            left: 7510.0,
                            top: 1414.0,
                            right: null,
                            bottom: null,
                            width: 109.0,
                            height: 464.0,
                            child: GeneratedLabelsWidget7(),
                          ),
                          Positioned(
                            left: 8326.0,
                            top: 1414.0,
                            right: null,
                            bottom: null,
                            width: 109.0,
                            height: 464.0,
                            child: GeneratedLabelsWidget8(),
                          ),
                          Positioned(
                            left: 3241.0,
                            top: 23.0,
                            right: null,
                            bottom: null,
                            width: 2423.0,
                            height: 1961.0,
                            child: GeneratedLabelsWidget9(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
