import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen07widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen07widget/generated/GeneratedUndraw_login_re_4vu21Widget.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen07widget/generated/GeneratedDeviceFrameComponentsWidget12.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen07widget/generated/GeneratedOneTimePasswordWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen07widget/generated/GeneratedPrevNextButtonWidget.dart';

/* Frame Sign Up Screen 07
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpScreen07Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: GeneratedPrevNextButtonWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 178.0,
                child: GeneratedOneTimePasswordWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 215.22976684570312,
                child: GeneratedUndraw_login_re_4vu21Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 52.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget12(),
              )
            ]),
      ),
    ));
  }
}
