import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword03widget/generated/GeneratedButton_sign_inWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword03widget/generated/GeneratedPasswordsuccesfullyresetWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword03widget/generated/GeneratedDeviceFrameComponentsWidget7.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword03widget/generated/GeneratedUndraw_forgot_password_re_hxwm1Widget.dart';

/* Frame Forgot Password 03
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPassword03Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 134.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 40.0,
                child: GeneratedButton_sign_inWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 26.0,
                child: GeneratedPasswordsuccesfullyresetWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 239.2450714111328,
                child: GeneratedUndraw_forgot_password_re_hxwm1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget7(),
              )
            ]),
      ),
    ));
  }
}
