import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedAlertWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedAdd_alertWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedNotification_importantWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedAuto_deleteWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedError_outlineWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedWarningWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedErrorWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedalertwidget/generated/GeneratedWarning_amberWidget.dart';

/* Frame Alert
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlertWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 504.0,
        height: 144.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 19.0,
                child: GeneratedAlertWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAdd_alertWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAuto_deleteWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedErrorWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedError_outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNotification_importantWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWarningWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.16666666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWarning_amberWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
