import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile01widget/generated/GeneratedProfileDetailsWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile01widget/generated/GeneratedProfileSummaryWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile01widget/generated/GeneratedEditImagePhotoWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile01widget/generated/GeneratedDeviceFrameComponentsWidget2.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile01widget/generated/GeneratedProfileVisibilityWidget.dart';

/* Frame Profile 01
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfile01Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 393.0,
                child: GeneratedProfileDetailsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 594.4375,
                right: null,
                bottom: null,
                width: 360.0,
                height: 190.125,
                child: GeneratedEditImagePhotoWidget(),
              ),
              Positioned(
                left: 79.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 160.0,
                child: GeneratedProfileSummaryWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 24.0,
                child: GeneratedProfileVisibilityWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget2(),
              )
            ]),
      ),
    ));
  }
}
