import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses0nwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitArcuintr.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses0nwidget/generated/GeneratedGraduationTrackWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses0nwidget/generated/GeneratedEnrolledCoursesDeetsWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses0nwidget/generated/GeneratedDeviceFrameComponentsWidget.dart';

/* Frame Courses 0n
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCourses0nWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 800.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 14.0,
                      top: 375.0,
                      right: null,
                      bottom: null,
                      width: 337.0,
                      height: 401.0,
                      child:
                          GeneratedLoremipsumdolorsitametconsecteturadipiscingelitArcuintr(),
                    )
                  ]),
            ),
            Positioned(
              left: 8.0,
              top: 345.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 19.0,
              child: GeneratedEnrolledCoursesDeetsWidget(),
            ),
            Positioned(
              left: 21.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 320.0,
              height: 240.0,
              child: GeneratedGraduationTrackWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0000305175781,
              height: 798.2329711914062,
              child: GeneratedDeviceFrameComponentsWidget(),
            )
          ]),
    ));
  }
}
