import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses00widget/generated/GeneratedDeviceFrameComponentsWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedcourses00widget/generated/GeneratedCoursesWidget.dart';

/* Frame Courses 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCourses00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 800.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 798.2329711914062,
                      child: GeneratedDeviceFrameComponentsWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 101.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 116.0,
              child: GeneratedCoursesWidget(),
            )
          ]),
    ));
  }
}
