import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generateddashboard03widget/generated/GeneratedHorizontalcard_enrolled_course_2Widget.dart';
import 'package:flutterapp/gradtrackapp/generateddashboard03widget/generated/GeneratedDeviceFrameComponentsWidget4.dart';
import 'package:flutterapp/gradtrackapp/generateddashboard03widget/generated/GeneratedFailedCoursesWidget.dart';

/* Frame Dashboard 03
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboard03Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 360.0,
                height: 800.0,
                child: ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 116.0,
                child: GeneratedFailedCoursesWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 240.0,
                child: GeneratedHorizontalcard_enrolled_course_2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0000305175781,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget4(),
              )
            ]),
      ),
    ));
  }
}
