import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedManage_searchWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedTable_restaurantWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBedroom_childWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedDoor_backWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedCoffeeWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedDoor_slidingWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBathroomWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedYardWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedLightWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBedroom_babyWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedCamera_outdoorWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedCamera_indoorWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedDiningWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedFlatwareWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedTable_barWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBlenderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBedroom_parentWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedWindowWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedCoffee_makerWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedDoorbellWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedShowerWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedGarageWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedPodcastsWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedDoor_frontWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedChairWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedLivingWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedBedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedFeedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsearchwidget/generated/GeneratedChair_altWidget.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 504.0,
        height: 240.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBathroomWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBedroom_babyWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBedroom_childWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBedroom_parentWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBlenderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCamera_indoorWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCamera_outdoorWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedChairWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.3,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedChair_altWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCoffeeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCoffee_makerWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDiningWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDoor_backWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDoor_frontWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDoor_slidingWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDoorbellWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFeedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFlatwareWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGarageWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLightWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLivingWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedManage_searchWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPodcastsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedShowerWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTable_barWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTable_restaurantWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWindowWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.1;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.7,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedYardWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
