import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword02widget/generated/GeneratedUndraw_forgot_password_re_hxwm1Widget1.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword02widget/generated/GeneratedDeviceFrameComponentsWidget8.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword02widget/generated/GeneratedButton_reset_pwdWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword02widget/generated/GeneratedPasswordWidget.dart';

/* Frame Forgot Password 02
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPassword02Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 105.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 40.0,
                child: GeneratedButton_reset_pwdWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 142.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 239.2450714111328,
                child: GeneratedUndraw_forgot_password_re_hxwm1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget8(),
              )
            ]),
      ),
    ));
  }
}
