import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStar_outlineWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedToggleWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStarWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStar_purple500Widget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedRadio_button_uncheckedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStar_borderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedRadio_button_checkedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedToggle_offWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedCheck_boxWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedToggle_onWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedIndeterminate_check_boxWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedCheck_box_outline_blankWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStar_border_purple500Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedtogglewidget/generated/GeneratedStar_halfWidget.dart';

/* Frame Toggle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedToggleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 504.0,
        height: 192.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedToggleWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCheck_boxWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCheck_box_outline_blankWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIndeterminate_check_boxWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRadio_button_checkedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRadio_button_uncheckedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStarWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStar_borderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStar_border_purple500Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStar_halfWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStar_outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStar_purple500Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToggle_offWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height = constraints.maxHeight * 0.125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToggle_onWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
