import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedsigninscreen00widget/generated/GeneratedDeviceFrameComponentsWidget11.dart';
import 'package:flutterapp/gradtrackapp/generatedsigninscreen00widget/generated/GeneratedFrame9Widget.dart';

/* Frame Sign In Screen 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignInScreen00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 359.5877990722656,
                height: 685.6639404296875,
                child: GeneratedFrame9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget11(),
              )
            ]),
      ),
    ));
  }
}
