import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen01widget/generated/GeneratedDeviceFrameComponentsWidget20.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen01widget/generated/GeneratedButton_sign_upWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen01widget/generated/GeneratedYoureenrolledintoAUniversityWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen01widget/generated/GeneratedUndraw_my_app_re_gxtj1Widget.dart';

/* Frame Enrollment Screen 01
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEnrollmentScreen01Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          decoration: BoxDecoration(
            border: Border.all(
              width: 1.0,
              color: Color.fromARGB(255, 0, 0, 0),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: null,
                  top: 0.0,
                  right: null,
                  bottom: 0.0,
                  width: 97.0,
                  height: null,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: 0.00,
                      z: 0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height = constraints.maxHeight * 0.05;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.56,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedButton_sign_upWidget2(),
                              ))
                        ]);
                      })),
                ),
                Positioned(
                  left: 23.0,
                  top: 400.0,
                  right: null,
                  bottom: null,
                  width: 316.0,
                  height: 30.0,
                  child: GeneratedYoureenrolledintoAUniversityWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 109.0,
                  right: null,
                  bottom: null,
                  width: 359.9117431640625,
                  height: 290.58837890625,
                  child: GeneratedUndraw_my_app_re_gxtj1Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 798.2329711914062,
                  child: GeneratedDeviceFrameComponentsWidget20(),
                )
              ]),
        ),
      ),
    ));
  }
}
