import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_circleWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedAttachmentWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedSnippet_folderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedWorkspacesWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFile_uploadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_zipWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedRequest_quoteWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDrive_file_move_rtlWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFile_download_offWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedText_snippetWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedTopicWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDifferenceWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_deleteWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_syncWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_queueWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFile_download_doneWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedRule_folderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDrive_file_moveWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_offWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedAttach_emailWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_uploadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedUpload_fileWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDownloadingWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDownload_doneWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFile_downloadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDrive_folder_uploadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedUploadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDrive_file_rename_outlineWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCreate_new_folderWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_openWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFormat_overlineWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFileWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedGrid_viewWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_copyWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDownloadWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_doneWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFile_openWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedDownload_for_offlineWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloudWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedCloud_downloadWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedApprovalWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_offWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedFolder_sharedWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedfilewidget/generated/GeneratedNewspaperWidget.dart';

/* Frame File
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 504.0,
        height: 336.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 19.0,
                child: GeneratedFileWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedApprovalWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAttach_emailWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAttachmentWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloudWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_circleWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_doneWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_downloadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_offWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_queueWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.21428571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_syncWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCloud_uploadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCreate_new_folderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDifferenceWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDownloadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDownload_doneWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDownload_for_offlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDownloadingWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDrive_file_moveWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDrive_file_move_rtlWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.35714285714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDrive_file_rename_outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDrive_folder_uploadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFile_downloadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFile_download_doneWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFile_download_offWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFile_openWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFile_uploadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_copyWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_deleteWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.5,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_offWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_openWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_sharedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFolder_zipWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFormat_overlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42857142857142855,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGrid_viewWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5238095238095238,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNewspaperWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6190476190476191,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRequest_quoteWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7142857142857143,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRule_folderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8095238095238095,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSnippet_folderWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9047619047619048,
                        y: constraints.maxHeight * 0.6428571428571429,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedText_snippetWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.047619047619047616,
                        y: constraints.maxHeight * 0.7857142857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTopicWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14285714285714285,
                        y: constraints.maxHeight * 0.7857142857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUploadWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.23809523809523808,
                        y: constraints.maxHeight * 0.7857142857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUpload_fileWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047619047619047616;

                  final double height =
                      constraints.maxHeight * 0.07142857142857142;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3333333333333333,
                        y: constraints.maxHeight * 0.7857142857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWorkspacesWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
