import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile00widget/generated/GeneratedProfileVisibilityWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile00widget/generated/GeneratedDeviceFrameComponentsWidget3.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile00widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile00widget/generated/GeneratedProfileSummaryWidget1.dart';
import 'package:flutterapp/gradtrackapp/generatedprofile00widget/generated/GeneratedProfileDetailsWidget2.dart';

/* Frame Profile 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfile00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 393.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 392.0,
                child: GeneratedProfileDetailsWidget2(),
              ),
              Positioned(
                left: 79.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 160.0,
                child: GeneratedProfileSummaryWidget1(),
              ),
              Positioned(
                left: 160.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 24.0,
                child: GeneratedProfileVisibilityWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget3(),
              )
            ]),
      ),
    ));
  }
}
