import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen00widget/generated/GeneratedDeviceFrameComponentsWidget19.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen00widget/generated/GeneratedUndraw_books_re_8gea1Widget6.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen00widget/generated/GeneratedPrevNextButtonWidget7.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen00widget/generated/GeneratedBiodata0InputWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedsignupscreen00widget/generated/GeneratedSignUpWidget7.dart';

/* Frame Sign Up Screen 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpScreen00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 260.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 40.0,
                child: GeneratedPrevNextButtonWidget7(),
              ),
              Positioned(
                left: 34.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 284.0,
                child: GeneratedBiodata0InputWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 228.7956085205078,
                child: GeneratedUndraw_books_re_8gea1Widget6(),
              ),
              Positioned(
                left: 28.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 52.0,
                child: GeneratedSignUpWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget19(),
              )
            ]),
      ),
    ));
  }
}
