import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedUndraw_my_app_re_gxtj1Widget1.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedButton_code_verificationWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedAlreadyenrolledWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedText_enrollment_codeWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedDeviceFrameComponentsWidget21.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/gradtrackapp/generatedenrollmentscreen00widget/generated/GeneratedSignInUpButtonWidget.dart';

/* Frame Enrollment Screen 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEnrollmentScreen00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          decoration: BoxDecoration(
            border: Border.all(
              width: 1.0,
              color: Color.fromARGB(255, 0, 0, 0),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 36.0,
                  top: 630.0,
                  right: null,
                  bottom: null,
                  width: 293.0,
                  height: 40.0,
                  child: GeneratedSignInUpButtonWidget(),
                ),
                Positioned(
                  left: 125.0,
                  top: 610.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 22.0,
                  child: GeneratedAlreadyenrolledWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.2361111111111111;

                    final double height = constraints.maxHeight * 0.05;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.3861111111111111,
                          y: constraints.maxHeight * 0.64125,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedButton_code_verificationWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 77.0,
                  top: 433.0,
                  right: null,
                  bottom: null,
                  width: 210.0,
                  height: 56.0,
                  child: GeneratedText_enrollment_codeWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 109.0,
                  right: null,
                  bottom: null,
                  width: 359.9117431640625,
                  height: 290.58837890625,
                  child: GeneratedUndraw_my_app_re_gxtj1Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 798.2329711914062,
                  child: GeneratedDeviceFrameComponentsWidget21(),
                )
              ]),
        ),
      ),
    ));
  }
}
