import 'package:flutter/material.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword00widget/generated/GeneratedUndraw_forgot_password_re_hxwm1Widget3.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword00widget/generated/GeneratedText_email_phoneWidget.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword00widget/generated/GeneratedDeviceFrameComponentsWidget10.dart';
import 'package:flutterapp/gradtrackapp/generatedforgotpassword00widget/generated/GeneratedButton_get_otpWidget.dart';

/* Frame Forgot Password 00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPassword00Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 129.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 40.0,
                child: GeneratedButton_get_otpWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 56.0,
                child: GeneratedText_email_phoneWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 239.2450714111328,
                child: GeneratedUndraw_forgot_password_re_hxwm1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 798.2329711914062,
                child: GeneratedDeviceFrameComponentsWidget10(),
              )
            ]),
      ),
    ));
  }
}
